### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by nobody5050**

### CODE REVIEW

**Review by carbonatedcaffeine — CHANGES_REQUESTED** [review]
This is not our license... Find the one on pangolin desktop and copy it here.

**Review by carbonatedcaffeine — APPROVED** [review]
Ok... now it's all good.

**Comment by nobody5050** [comment]
i was using the original license that qemu is under. whatever its fine

**Comment by carbonatedcaffeine** [comment]
Srry..  whoops.

**Pull request merged**
